### ISSUE TITLE
Challenging invalid transactions

### ISSUE THREAD

**Issue by keyvank** [luciditytech/lucidity-plasma-cash#9]
Thank you for this great project! Seems much simpler than other Plasma Cash implementations :+1: 
I just didn't understand how this scenario is going to be handled in your contract:

1. Operator creates an invalid transaction out of the air, with his own signature, saying that he owns that coin and includes it in the merkle-root of a block.
2. Operator `startTxExit`s that coin.
3. How can the real owner of that coin challenge that exit? As far as I understand, by calling `challengeTxExit` you can just invalidate an exit by providing a transaction that spends the exiting transaction.

EDIT:
I just saw your explanation on ethresear.ch, seems clear to me know. Thank you!

> User can start exit on that transaction, but then the right owner will start an exit on previous one and he has the priority for exit. It is not possible to challenge right owner with invalid transaction, because plasma root for targetBlock will not match.

**Comment by DZariusz** [comment]
Your welcome :-)
